### ISSUE TITLE
Proper playlist management

### ISSUE THREAD

**Issue by unusualbob** [martindale/soundtrack.io#25] opened 2013-07-19 17:16 UTC
User playlists should be accessible via the UI. This should likely be done via angular.js.

Features that should be included:
* Track preview
* pdj import
* add track to room

**Comment by martindale** [comment] 2015-01-11 21:47
Largely fixed with [the launch of "Sets"](https://twitter.com/soundtrackio/status/551199088767950848), but closing as a duplicate of #14.

**Closed by martindale** 2015-01-11 21:47 UTC
